### ISSUE TITLE
Error enabling the plugin

### ISSUE THREAD

**Issue by ghost** [Begad666/cps#13]
**Config**
This is my [config file](https://pastebin.com/bx1zxRY6) and this is my [WaterFall console](https://pastebin.com/MKPvtpcV).

**Screenshots**

**Info (please complete the following information):**
 - OS: Windows
 - Java Version: 1.8.0_261
 - Plugin Version: v3.0
 - BungeeCord Version: I don't really use Bungee, I use WaterFall #370

**Additional context**
I installed CoreAPI in both my Spigot and BungeeCord server, but it does not seem to fix the issue. I even reinstalled the plugin, use the normal config file, but it does not fix the issue.

**Comment by Begad666** [comment]
Can you upload the two jars here? For me it is working.
You don't need to place CoreAPI in Spigot plugins.
And you have some problems with your config.

**Comment by Begad666** [comment]
As I can see on your console log, Waterfall is loading the Spigot one of the plugin, which is weird because I tested it right now with the same version and it worked

**Comment by ghost** [comment]
[Plugins.zip](https://github.com/Begad666/cps/files/5145148/Plugins.zip)
This is CPS and CoreAPI (I did not edit anything yet, but it still doesn't work).

Also, when I use my backed-up v2.0 CPS, it works perfectly fine without any issues.

**Comment by Begad666** [comment]
The CoreAPI plugin downloaded is not mine, sorry for not putting a link in the home page, https://www.spigotmc.org/resources/coreapi.82952/

**Comment by Begad666** [comment]
Also your config file has some problems, you shouldn't delete allowed-protocols section, as its required to block users who use a not supported minecraft version by your server.
And default-protocol shouldn't also be deleted, this is what version your server is.
I might change the plugin to add a config property to allow all versions.

**Comment by ghost** [comment]
> Also your config file has some problems, you shouldn't delete allowed-protocols section, as its required to block users who use a not supported minecraft version by your server.
> And default-protocol shouldn't also be deleted, this is what version your server is.
> I might change the plugin to add a config property to allow all versions.

Thanks for the help. I apreciate it!

**Comment by Begad666** [comment]
No problem.
