### ISSUE TITLE
Bug Found, Can't Push config in database

### ISSUE THREAD

**Issue by MastoryMd5** [Begad666/cps#18]
When i try to send the config in to the database it gives me this error.

https://hastebin.com/babakebame.sql

**Comment by Begad666** [comment]
My way of uploading the config isn't working, I will fix it tomorrow.
Sorry for the bugs.

**Comment by Begad666** [comment]
For now, I don't have a temporary resolution to the problem.

**Comment by Begad666** [comment]
I think I fixed it, I tried pushing and pulling and everything works.

**Comment by MastoryMd5** [comment]
Thanks for your work!
