### ISSUE TITLE
Bug Found Playercount does not report correctly with RedisBungee

### ISSUE THREAD

**Issue by MastoryMd5** [Begad666/cps#19]
I might be particularly unlucky but i found another small bug with CPS.

![2401e3dc0472d0eb300098e8f9bfca24](https://user-images.githubusercontent.com/17986972/96506912-b7806880-1258-11eb-86ee-6e30f6bede48.png)

The server on the top is using CPS the server on the bottom is using cleanmotd

As you can see i don't get the same playercount, actually the server with CPS gives the playercount of the single proxy not of all the proxies connected with redisbungee

**Comment by Begad666** [comment]
So I need to add redisbungee support and change how the plugin sends player counts and possibly, player names if enabled.

**Comment by Begad666** [comment]
I think I have done the integration but if you can check it out use this version.
[CustomProtocolSettings.zip](https://github.com/Begad666/cps/files/5405211/CustomProtocolSettings.zip)

.

**Comment by Begad666** [comment]
And also a new way to get ping from other servers.
Just enable settings.ping-unstable-redisbungee .

**Comment by MastoryMd5** [comment]
Perfect, the patch works amazingly!

**Comment by Begad666** [comment]
Nice, now I should make the other things to use RedisBungee and that will be it.
And what about the ping command?

**Comment by MastoryMd5** [comment]
The ping works but i have to test it to see if it's actually "unstable"

**Comment by Begad666** [comment]
That's good

**Comment by MastoryMd5** [comment]
Okay actually the ping works on the same bungeecord but if i'm on one proxy and the player is in another proxy i can't ping the player and when i send the command i don't get an answer

**Comment by Begad666** [comment]
That's probably because it doesn't process the message right, gotta check the problem.

**Comment by Begad666** [comment]
Try this and check all the consoles. This one will send debug messages.
[CPS.zip](https://github.com/Begad666/cps/files/5405415/CPS.zip)

**Comment by MastoryMd5** [comment]
Proxy 1 i do the command with my account, on the console nothing appears.
Proxy 2 the console receives the command to get the ping for the player but no message appears
`[CustomProtocolSettings]: Received command to get ping for NullTheElif`

**Comment by Begad666** [comment]
Check the server id for proxy 1, if it matches the log output, I will need to install redis to debug it.
[CPS2.zip](https://github.com/Begad666/cps/files/5405428/CPS2.zip)

**Comment by MastoryMd5** [comment]
Proxy 2 i do the command with my account, on the console nothing appears.
Proxy 1 Console`[CustomProtocolSettings]: Received command to get ping for NullTheElif`

Proxy 2 console `[CustomProtocolSettings]: Received ping result for java2, id NullTheElif
`

Proxy 1 is java1 and Proxy 2 is java2

**Comment by MastoryMd5** [comment]
I've switched proxy but it should be the same

**Comment by Begad666** [comment]
~~java2 is your proxy 1 id right?~~

**Comment by Begad666** [comment]
nvm

**Comment by Begad666** [comment]
This one should work, messed up the indexes.
[CPS3.zip](https://github.com/Begad666/cps/files/5405470/CPS3.zip)

**Comment by MastoryMd5** [comment]
Now i get this error
https://hastebin.com/wupojoguco.properties

**Comment by Begad666** [comment]
I am sorry but this should be the last time.
[NPEFix.zip](https://github.com/Begad666/cps/files/5405483/NPEFix.zip)

**Comment by MastoryMd5** [comment]
![e81b96fa53b9ee1ebff1f0560c35ada7](https://user-images.githubusercontent.com/17986972/96524557-e8709580-1278-11eb-9612-bbe5f3ebebfd.png)
It works!

**Comment by Begad666** [comment]
"Perhaps", I mean, it might glitch if too many users are using the command, didn't test it, if it doesn't glitch, then I might remove the unstable and just ping-redisbungee-support

**Comment by Begad666** [comment]
But for now, I think it finished

**Comment by Begad666** [comment]
And a quick thing, reloading breaks redisbungee integration, just saw it now, will get fixed.
