### ISSUE TITLE
Bugs Found | Lang and pull problem

### ISSUE THREAD

**Issue by MastoryMd5** [Begad666/cps#21]
The messages are duplicated, although in the config i set up the "it" lang in the console i can see the translated message and the default one even after deleting en.yml.

![a126126a8d0f48b5b63a5955b872ee10](https://user-images.githubusercontent.com/17986972/96520734-fc63c980-126f-11eb-9d53-631126e8f55c.png)

Second problem happens when pulling from database the config, after the reload the plugin shutsdown and commands motd etc don't work

**Comment by Begad666** [comment]
I made it send also a message to the console, try in game

**Comment by Begad666** [comment]
"I hope I didn't create another bug"

**Comment by Begad666** [comment]
But did you change the language section in the config?

**Comment by MastoryMd5** [comment]
Yes, the languace is in 'it', i will try now with the in-game commands

**Comment by Begad666** [comment]
That's weird, it always uses the language section in the config.
I tried changing the values and it worked. Might be something related to loading files other than "en"

**Comment by Begad666** [comment]
I just tried creating a new file, renaming it and changing everything in it and it worked.
If it doesn't find the message, it sends a hardcoded message, that's why when you deleted the en.yml file, it's still sending like it is there.

**Comment by MastoryMd5** [comment]
Okay so the important thing is to not delete en.yml

**Comment by Begad666** [comment]
Nope it's not important, you can delete it.

**Comment by Begad666** [comment]
Did you fix this problem?

**Comment by Begad666** [comment]
Tomorrow should be the new version.
I have to go.
